<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <script src="lib/Promise.js"></script> -->

    <!-- <script>
        // 直接调用,里面的this指向window
        const p = new Promise((resolve, reject) => {
            // 加setTimeout假设先定义回调,后改promise状态
            setTimeout(() => {
                console.log('setTimeout')
                // resolve(1)
                reject(2);
            }, 100)
        }).then(
            value => {
                console.log('onResolved()-1', value);
            },
            reason => {
                console.log('onRejected()-1', reason);
                // throw 1
                return new Promise((resolve, reject) => reject(1))
            }
        ).then(
            value => {
                console.log('onResolved()-2', value);
            },
            reason => {
                console.log('onRejected()-2', reason);
                throw 2
            }
        ).catch(e => {
            console.log("catch", e);
        })
    </script> -->

    <script>
        // const p1 = Promise.resolve(1);

        // const p2 = Promise.reject(2);

        // // 如果p3成功,传递的value就是Promise.resolve(3)传过来的value
        // const p3 = Promise.resolve(Promise.resolve(3));

        // // 如果p4失败,传递的value就是Promise.reject(4)传过来的value
        // const p4 = Promise.reject(Promise.reject(4));

        // p1.then(
        //     value => {
        //         console.log('p1', value)
        //     }
        // )

        // p3.then(
        //     value => {
        //         console.log('p3', value)
        //     }
        // )

        // p4.catch(
        //     reason => {
        //         console.log('p4', reason)
        //     }
        // )

        const p1 = new Promise((resolve, reject) => {
            const a = 2;
            if (a%2 === 0) {
                // throw new Error('p1-catch');
                resolve(2);
            }else {
                reject(0)
            }
        }).then(
            value => {
                console.log('p1-value', value);
                return value;
            },
            e => console.log('p1-e', e)
        )

        const p2 = new Promise((resolve, reject) => {
            const a = 1;
            if (a%2 === 0) {
                throw new Error('p2-catch');
                // resolve(2);
            }else {
                reject(0)
            }
        }).then(
            value => {
                console.log('p2-value', value);
                return value;
            },
            e => {
                console.log('p2-e', e);
                // return e;
                // throw new Error('p2-catch');
                // return Promise.reject('p2-catch')
                Promise.reject('p2-catch')
            }
        )
        .catch (
            e => {
                console.log('p2-catch', e);
                // return 'p2-catch'
                // throw new Error('p2-catch');
                // return Promise.reject('p2-catch')
                // return Promise.reject('p2-catch')
            }
        )

        Promise.all([
            p1.catch(e => {console.log('p1-all')}),
            p2.catch(e => {console.log('p2-all')}),
        ]).catch(e => console.log('alle'))
        .then(
            value => console.log('succ4ess', value)
        )

    </script>
</body>
</html>